version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DEBUG: 'true'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./static:/static  # Mount local static files directory
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - pms-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432
    networks:
      - pms-network

volumes:
  postgres_data:

networks:
  pms-network:
    name: pms-network
